using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using System.Data.OleDb;
namespace WindowsFormsApplication2
{
	public partial class AdminProductsCustomControl : UserControl
	{
		private OleDbConnection connection = new OleDbConnection();

		public AdminProductsCustomControl()
		{
			InitializeComponent();
			connection.ConnectionString = @"Provider=Microsoft.ACE.OLEDB.12.0;Data Source=F:\Study\GSU Senior Project and Seminar 4900\Project\WindowsFormsApplication2\DNS.accdb;
Persist Security Info=False;";
		}

		private void productBindingNavigatorSaveItem_Click(object sender, EventArgs e)
		{
			this.Validate();
			this.productBindingSource.EndEdit();
			this.tableAdapterManager.UpdateAll(this.dNSDataSet);

		}

		
		private void btnFetch_Click(object sender, EventArgs e)
		{
			try
			{
				cmbProductID.Items.Clear();
				txtPrice.Text = "";
				txtProductName.Text = "";
				cmbSubCateg.Text = "";
				cmbCategory.Text = "";
				cmbProductID.Text = "";
				connection.Open();
				OleDbCommand command = new OleDbCommand();
				command.Connection = connection;
				string query = "select * from Product";
				command.CommandText = query;

				OleDbDataAdapter da = new OleDbDataAdapter(command);
				DataTable dt = new DataTable();
				da.Fill(dt);
				productDataGridView.DataSource = dt;

				//For combo box:
				OleDbDataReader reader = command.ExecuteReader();
				while (reader.Read())
				{
					cmbProductID.Items.Add(reader.GetInt32(0));
					
				}

				connection.Close();
			}
			catch(Exception ex)
			{
				MessageBox.Show(ex + "");
			}
		}
		
		private void cmbProductID_SelectedIndexChanged(object sender, EventArgs e)
		{
			try
			{
				connection.Open();
				OleDbCommand command = new OleDbCommand();
				command.Connection = connection;
				command.CommandText = "select * from Product where productID=" + Int32.Parse(cmbProductID.Text) + "";

				OleDbDataReader reader = command.ExecuteReader();
				while (reader.Read())
				{
				
					txtProductName.Text = reader.GetString(1);
					txtPrice.Text = reader.GetDouble(2).ToString();
					cmbCategory.Text = reader.GetString(3);
					cmbSubCateg.Text = reader.GetString(4);
				}

				connection.Close();
			}
			catch(Exception ex)
			{
				MessageBox.Show(ex + "");
			}
		}

		private void btnAdd_Click(object sender, EventArgs e)
		{
			try
			{
				connection.Open();
				OleDbCommand command = new OleDbCommand();
				command.Connection = connection;
				command.CommandText = "insert into Product (productName,productPrice,productCategory,productSubCategory) values('" + txtProductName.Text + "','" + txtPrice.Text + "','" + cmbCategory.Text + "','" + cmbSubCateg.Text + "')";
				command.ExecuteNonQuery();
				MessageBox.Show("Data Saved");
				connection.Close();
			}
			catch(Exception ex)
			{
				MessageBox.Show("Error" + ex);
			}
			
		}

		private void btnUpdate_Click(object sender, EventArgs e)
		{
			MessageBox.Show("Please Delete and Add new record. I am too lazy to implement this.", "Error generated by Unpaid Employee!");
		}

		private void btnDelete_Click(object sender, EventArgs e)
		{
			try
			{
				if (MessageBox.Show("Are you sure you want to delete product ID # " + cmbProductID.Text + "?", "Confirm Delete", MessageBoxButtons.YesNo) == DialogResult.Yes)
				{
					connection.Open();
					OleDbCommand command = new OleDbCommand();
					command.Connection = connection;
					
					command.CommandText = "delete * from product WHERE productID=" + Int32.Parse(cmbProductID.Text) + "";
					OleDbDataReader reader = command.ExecuteReader();
					MessageBox.Show("Removed from Product successfully!");
					connection.Close();
					//cmbProductID.SelectedIndex = -1;

				}
			}
			catch (Exception ex)
			{
				MessageBox.Show("Error in deleting the object" + ex);
			}

		}
	}
}
